
version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: dani-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=projetodani
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
      ports:
        - "3307:3306"

